export const IPC_CHANNELS = {
  appGetVersion: 'app:get-version',
  appGetElectronVersion: 'app:get-electron-version',
  appGetRecoverySnapshot: 'app:get-recovery-snapshot',
  appAckRecoverySnapshot: 'app:ack-recovery-snapshot',
  appOpenExternal: 'app:open-external',
  libraryList: 'library:list',
  librarySave: 'library:save',
  libraryDelete: 'library:delete',
  componentList: 'component:list',
  componentSave: 'component:save',
  componentDelete: 'component:delete',
  componentRestore: 'component:restore',
  componentFinalizeDelete: 'component:finalize-delete',
  componentReorder: 'component:reorder',
  componentSearch: 'component:search',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  componentImportHtml: 'component:import-html',
  clipboardWriteText: 'clipboard:write-text',
  exportSaveStandalone: 'export:save-standalone',
  exportSaveCss: 'export:save-css',
  previewConfigureNetwork: 'preview:configure-network',
  previewReleaseNetwork: 'preview:release-network',
} as const;
